/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_EXAMPLE_EXAMPLE_SHADES_SHADES_PB_H_INCLUDED
#define PB_EXAMPLE_EXAMPLE_SHADES_SHADES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _example_Adjustment {
  int32_t pin;
  int32_t duration_ms;
  int32_t duty_cycle;
} example_Adjustment;

#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define example_Adjustment_init_default                                        \
  { 0, 0, 0 }
#define example_Adjustment_init_zero                                           \
  { 0, 0, 0 }

/* Field tags (for use in manual encoding/decoding) */
#define example_Adjustment_pin_tag 1
#define example_Adjustment_duration_ms_tag 2
#define example_Adjustment_duty_cycle_tag 3

/* Struct field encoding specification for nanopb */
#define example_Adjustment_FIELDLIST(X, a)                                     \
  X(a, STATIC, SINGULAR, INT32, pin, 1)                                        \
  X(a, STATIC, SINGULAR, INT32, duration_ms, 2)                                \
  X(a, STATIC, SINGULAR, INT32, duty_cycle, 3)
#define example_Adjustment_CALLBACK NULL
#define example_Adjustment_DEFAULT NULL

extern const pb_msgdesc_t example_Adjustment_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define example_Adjustment_fields &example_Adjustment_msg

/* Maximum encoded size of messages (where known) */
#define example_Adjustment_size 33

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
